services:
  postgres:
    image: postgres:16.4
    container_name: proof
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: proof
    volumes:
      - ./.sst/storage/postgres:/var/lib/postgresql/data
    restart: unless-stopped
